modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "todolist"
version = "${version}"
displayTest = "IGNORE_SERVER_VERSION"
displayName = "todolist.name"
logoFile = "assets/todolist/icon.png"
authors = "spacehouse"
description = "todolist.description"

[[dependencies.todolist]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.todolist]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
