# Mod Properties
mod_version = 1.4.2
maven_group = com.todolist
archives_name = todolist

# Minecraft Properties
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.3:v2
loader_version = 0.18.1
fabric_api_version = 0.116.9+1.21.1
forge_version = 52.1.10
neoforge_version = 21.1.219
modmenu_version = 11.0.3
loom_version = 1.17.491

# Gradle Properties
org.gradle.jvmargs = -Xmx4G -Dfile.encoding=UTF-8
