modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "todolist"
version = "${version}"
displayName = "todolist.name"
logoFile = "assets/todolist/icon.png"
authors = "spacehouse"
description = "todolist.description"

[[dependencies.todolist]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.todolist]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
